import { Mock } from 'protractor/built/driverProviders'
/*import {Trip} from './trip'
export const mockTrips : Trip[] = [
    {
        id: "0",
        name: "Winter in Oslo",
        country:"Norway",
        dateFrom: new Date(2021, 2, 12),
        dateTo: new Date(2021, 9, 12),
        price: 1227.00,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ",        
        photoURL: "https://tripkiller.pl/images/tours/ms_1520612669-oslo-norwey-1-jpg.jpg",
        places: 12,
        booked: 10,
        rating: 4.8,
        votes: 10,
        inCart:0
        
    },
    {
        id:"1",
        name: "Gaudi's Barcelona",
        country:"Spain",
        dateFrom: (new Date(2020, 11, 2)),
        dateTo: new Date(2020, 11, 14),
        price: 1222.00,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        photoURL: "https://f4fcdn.eu/wp-content/uploads/2020/07/shutterstock_552368572-2.jpg",
        places: 12,
        booked: 12,
        rating: 4.0,
        votes: 12,
        inCart:0
    },
    {
        id: "2",
        name: "Swedish fjiords",
        country:"Sweden",
        dateFrom: (new Date(2020, 12, 20)),
        dateTo: new Date(2020, 12, 30),
        price: 1000.00,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ",
        photoURL:"https://www.telegraph.co.uk/content/dam/Travel/Cruise/Ocean/Sunnylvsfjorden-iStock.jpg",
        places: 12,
        booked: 10,
        rating: 4.8,
        votes: 20,
        inCart:0
    },
    {
        id: "3",
        name: "Roman Holiday",
        country:"Italy",
        dateFrom: (new Date(2021, 11, 1)),
        dateTo: new Date(2021, 11, 8),
        price: 922.00,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ",
        photoURL: "https://wlochy.edu.pl/wp-content/uploads/2019/09/Rzym-panorama.jpg",
        places: 12,
        booked: 5,
        rating: 4.4,
        votes: 16,
        inCart:0
    },
    {
        id: "4",
        name: "Explore Berlin",
        country:"Germany",
        dateFrom: (new Date(2021, 10, 9)),
        dateTo: new Date(2021, 10, 18),
        price: 222.00,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ",
        photoURL: "https://i.iplsc.com/brama-brandenburska/0003K1FMG0M6X9HP-C122-F4.jpg",
        places: 82,
        booked: 18,
        rating: 3.9,
        votes: 18,
        inCart:0
    },
    {
        id: "5",
        name: "Crete relax",
        country:"Greece",
        dateFrom: (new Date(2021, 6, 19)),
        dateTo: new Date(2021, 6, 28),
        price: 922.00,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ",
        photoURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_8cOGalslmfhNhTNDT2PtBYyn3TFgYf1ZJg&usqp=CAU",
        places: 24,
        booked: 19,
        rating: 4.3,
        votes: 21,
        inCart:0
    },
    {
        id: "6",
        name: "Hot Springs Patch",
        country:"Iceland",
        dateFrom: (new Date(2021, 1, 9)),
        dateTo: new Date(2021, 1, 18),
        price: 5142.00,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ",
        photoURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN3Pp_71EosMkClLXrJWy2G067YmPZno_zPA&usqp=CAU",
        places: 32,
        booked: 21,
        rating: 4.9,
        votes: 58,
        inCart:0
    },
    {
        id: "7",
        name: "Highlands of Scotland",
        country:"UK",
        dateFrom: (new Date(2022, 8, 29)),
        dateTo: new Date(2022, 9, 18),
        price: 2322.00,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ",
        photoURL: "https://cdn-image.departures.com/sites/default/files/1545062596/quiraing-trotternish-landscape-isle-skye-scotland-uk-SCOT1218.jpg",
        places: 43,
        booked: 11,
        rating: 3.8,
        votes: 38,
        inCart:0
    },
    {
        id: "8",
        name: "Castle of Loire Valley",
        country:"France",
        dateFrom: (new Date(2021, 11, 19)),
        dateTo: new Date(2021, 11, 28),
        price: 1422.00,
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. ",
        photoURL: "https://media.tacdn.com/media/attractions-splice-spp-674x446/06/71/05/5d.jpg",
        places: 82,
        booked: 18,
        rating: 3.9,
        votes: 18,
        inCart:0
    },
]*/